### ISSUE TITLE
Tesztesetek

### ISSUE THREAD

**Issue by ntopee** [ntopee/Projlab#13]
Tesztesetek megírása, amik végigmenek bizonyos szekvenciákon, szükség esetén bemenetet kérnek felhasználótól.

**Comment by bende01** [comment]
1. Player megtol egy Boxot
2. Egy Box megtol egy Boxot
3/4. Player neki megy a falnak/oszlopnak
5/6. Egy box neki megy a falnak/oszlopnak
7. Egy box rámegy a goalra
8. Egy Player lyukba esik
9. Egy box lyukba esik
10. Egy box rámegy a switchre
11. Egy Player találkozik egy playerrel
12. Switch lyukakat aktival
13. Player + switch
14. Player + goal

**Comment by bende01** [comment]
1-es Done

**Comment by AcidicNut** [comment]
2-es Done

**Comment by 1nco** [comment]
Egy box lyukba esik  = > eddig done

**Comment by june9666** [comment]
10.(8 switch) Done

**Comment by 1nco** [comment]
8,9,11,12 van hatra

**Comment by AcidicNut** [comment]
Done

**Comment by 1nco** [comment]
done!
