### ISSUE TITLE
Szekvencia diagramok

### ISSUE THREAD

**Issue by ntopee** [ntopee/Projlab#20]
Eredetiben (kész analízis modell, nem a hatvanx darab shit) meg kell nézni melyik szekvenciát befolyásolja #mézeszsírosgeci meg hogy #kraftkellatoláshoz, azokat modderálni és feltolni dokumentációba.
+ 2 special szekvencia, amit meg kell csinálni:
Munkás-láda-láda
Munkás-láda-munkás-láda

**Comment by 1nco** [comment]
//Box hitBy Box kell box hitby player mintájára (az első hitbynál force lesz, és nem p. strength ennyia  kül.)
Box Hitby Obstacle
Box hits Switch
Obstacle Hitby Player
Box hits goal
Palyer falls into a Hole
+ a 2 speckó szekvenci (lásd feljebb) 

Annyi a dolog, hogy a CollideWith-et kiszeded a meglévő szekvenciából, és az Add fv az opt előtt visszatér, és úgy hívódik meg utána miután az add visszatért a hitby. Ennyi a magic, de raktam fel pár készet már doksiba, azok alapján lehet csinálni. 

++Annyi, hogy ha Player hív meg egy HitBy-t akkor p.strength-et írsz a HitBy-ba, és ha Box hív meg HitBy-t vagy valami más,. akkor force-ot, ennyi. Ha kérdés van, elmagyarázom h mizu van velük.

- Pacso
