### ISSUE TITLE
Végleges program, összes teszteset ellenőrzése

### ISSUE THREAD

**Issue by ntopee** [ntopee/Projlab#5]
Tesztesetek kitalálása/megírása.

**Comment by june9666** [comment]
Pontosan melyik szekvenciákhoz?

**Comment by june9666** [comment]
Mit kell tesztelni pontosan?

**Comment by ntopee** [comment]
Konzol elindul és megkérdezi melyik tesztesetet akar futtatni, választ majd meghívja azt a függvényt. Eldöntendő dolgoknál (pl nem tudjuk van-e valami a következő tileon) akkor ezt felhasználótól megkérdezzük eldöntendő kérdéssel (y/n)
tehát boxtolósnál pl megkérdezzük hogy kovi tileon van-e box, lyukas tesztnel hogy van-e lyuk stb.
Mintának jók előző évek megoldásai vikwikin.

**Comment by ntopee** [comment]
kimeneten látszódnnak függvényhívások meg visszatérések ez a magic, ezeket már megírtuk
