### ISSUE TITLE
Rücsök

### ISSUE THREAD

**Issue by AcidicNut** [ntopee/Projlab#8]
https://www.youtube.com/watch?v=VUHXqSUgXQs

**Comment by AcidicNut** [comment]
Derítsd ki melyik házba tartozol, mi a patronusod, milyen a pálcád!
https://my.pottermore.com/user-profile

**Comment by ntopee** [comment]
Legnagyobb rücsök valaha:
https://github.com/ntopee/Projlab/projects/2
